- name: Administrar servidores en DigitalOcean
  hosts: all
  become: yes  # Añade esta línea para ejecutar todas las tareas con privilegios de superusuario
  tasks:
    - name: Clonar repositorio
      git:
        repo: https://github.com/Luisvaldez04/GOLANG-APP-
        dest: /home/luisvaldez04/GOLANG-APP-

    - name: Build and Start Docker container
      shell: |
        cd /home/luisvaldez04/GOLANG-APP-
        docker-compose down
        docker-compose build
        docker-compose up -d
